name: Linting and code quality check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: mundialis/github-workflows/.github/workflows/linting.yml@main
    with:
      # set pylint-version to empty string to skip the pylint workflow
      pylint-version: ''
      black-version: ''
      ruff-version: ''
      VALIDATE_DOCKERFILE_HADOLINT: false
      VALIDATE_JSON: false
